# Generated by Django 4.2.4 on 2023-11-10 13:47

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], verbose_name='Gender')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
                ('client_level', models.IntegerField(choices=[(0, 'Standard'), (1, 'Bronze'), (2, 'Silver'), (3, 'Gold'), (4, 'VIP')], default=0, verbose_name='Client Level')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Points')),
                ('referral_program_active', models.BooleanField(default=True, verbose_name='Referral Program Active')),
                ('points_system_active', models.BooleanField(default=True, verbose_name='Points System Active')),
                ('manual_level_set', models.BooleanField(default=False, verbose_name='Level Set Manually')),
                ('referred_clients_count', models.PositiveIntegerField(default=0, verbose_name='Referred Clients Count')),
                ('withdrawal_possible', models.BooleanField(default=False, verbose_name='Can Withdraw Funds')),
                ('is_company', models.BooleanField(default=False, verbose_name='Is Company')),
                ('company_password_hash', models.CharField(max_length=128, verbose_name='Company Password Hash')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClientLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Client Level')),
                ('required_points', models.PositiveIntegerField(verbose_name='Required Points')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='Total Points in Fund')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Representative Name')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('representative_password_hash', models.CharField(max_length=128, verbose_name='Representative Password Hash')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='custom_users.client', verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_level_percentage', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='First level referral percentage')),
                ('second_level_percentage', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Second level referral percentage')),
                ('purchase_percentage_to_fund', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Percentage of purchase to the fund')),
                ('system_active', models.BooleanField(default=True, verbose_name='Referral System Active')),
            ],
            options={
                'verbose_name': 'Referral Configuration',
                'verbose_name_plural': 'Referral Configurations',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_users.client', verbose_name='Client')),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_users.companyrepresentative', verbose_name='Company Representative')),
            ],
        ),
        migrations.CreateModel(
            name='ClientLevelReferralPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Referral Percentage')),
                ('client_level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='custom_users.clientlevel', verbose_name='Client Level')),
            ],
            options={
                'verbose_name': 'Client Level Referral Percentage',
                'verbose_name_plural': 'Client Level Referral Percentages',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='current_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_users.clientlevel', verbose_name='Current Level'),
        ),
        migrations.AddField(
            model_name='client',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_clients', to='custom_users.client', verbose_name='Referrer'),
        ),
    ]
