# Generated by Django 4.2.4 on 2023-11-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientlevelreferralpercentage',
            name='client_level',
        ),
        migrations.DeleteModel(
            name='CompanyFund',
        ),
        migrations.RemoveField(
            model_name='companyrepresentative',
            name='client',
        ),
        migrations.DeleteModel(
            name='ReferralConfig',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='client',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_level',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_password_hash',
        ),
        migrations.RemoveField(
            model_name='client',
            name='current_level',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='client',
            name='manual_level_set',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='points',
        ),
        migrations.RemoveField(
            model_name='client',
            name='points_system_active',
        ),
        migrations.RemoveField(
            model_name='client',
            name='referral_program_active',
        ),
        migrations.RemoveField(
            model_name='client',
            name='referred_clients_count',
        ),
        migrations.RemoveField(
            model_name='client',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='client',
            name='withdrawal_possible',
        ),
        migrations.AddField(
            model_name='client',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Information'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_line1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_line2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='client',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Customer Email'),
        ),
        migrations.AddField(
            model_name='client',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Name'),
        ),
        migrations.AddField(
            model_name='client',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Phone'),
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], null=True, verbose_name='Gender'),
        ),
        migrations.DeleteModel(
            name='ClientLevel',
        ),
        migrations.DeleteModel(
            name='ClientLevelReferralPercentage',
        ),
        migrations.DeleteModel(
            name='CompanyRepresentative',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
