# Generated by Django 4.2.4 on 2023-11-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0003_remove_client_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='tax_exemption_document',
            field=models.FileField(blank=True, null=True, upload_to='tax_documents/', verbose_name='Tax Exemption Document'),
        ),
    ]
