# Generated by Django 4.2.4 on 2023-09-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWepSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
