# Generated by Django 4.2.4 on 2023-09-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainWepSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsize',
            old_name='sku',
            new_name='size_sku',
        ),
    ]
