# Generated by Django 4.2.4 on 2023-11-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWepSite', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sizes/'),
        ),
    ]
