# Generated by Django 4.2.4 on 2023-09-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWepSite', '0002_rename_sku_productsize_size_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='price',
        ),
        migrations.AddField(
            model_name='productsize',
            name='size_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
