# Generated by Django 4.2.4 on 2023-09-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWepSite', '0003_remove_productsize_price_productsize_size_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
