# Generated by Django 4.2.4 on 2023-09-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainWepSite', '0004_orderitem_order_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderstatushistory',
            name='order',
        ),
    ]
