# Generated by Django 4.2.4 on 2023-11-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWepSite', '0005_alter_productsize_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
