# Generated by Django 4.2.4 on 2023-11-20 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0003_remove_client_additional_info_and_more'),
        ('MainWepSite', '0008_tag_blogpost_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_users.client'),
        ),
    ]
