# Generated by Django 4.2.4 on 2023-11-22 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainWepSite', '0010_blogpostimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
    ]
