# Generated by Django 4.2.4 on 2023-11-27 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0004_deliveryaddress_tax_exemption_document'),
        ('orders', '0002_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='custom_users.deliveryaddress'),
        ),
    ]
