# Generated by Django 4.2.4 on 2023-09-23 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainOffice', '0001_initial'),
        ('Warehouse1', '0002_driver_warehousesupervisor_warehouseworker'),
        ('orders', '0002_order_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='operator',
        ),
        migrations.AddField(
            model_name='order',
            name='accounts_payable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainOffice.accountspayable'),
        ),
        migrations.AddField(
            model_name='order',
            name='accounts_receivable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainOffice.accountsreceivable'),
        ),
        migrations.AddField(
            model_name='order',
            name='accounts_receivable_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainOffice.accountsreceivablemanager'),
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Warehouse1.driver'),
        ),
        migrations.AddField(
            model_name='order',
            name='operational_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainOffice.operationalmanager'),
        ),
        migrations.AddField(
            model_name='order',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainOffice.president'),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse_Worker_Driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Warehouse1.warehouseworkerdriver'),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Warehouse1.warehousesupervisor'),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Warehouse1.warehouseworker'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Получен'), ('OperatorReview', 'Обзор оператора'), ('WarehouseProcessing', 'Обработка на складе'), ('Delivery', 'Доставка'), ('Completed', 'Завершен')], default='Received', max_length=20),
        ),
    ]
