# Generated by Django 4.2.4 on 2023-09-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_operator_order_accounts_payable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Получен'), ('OperatorReview', 'Обзор оператора'), ('WarehouseProcessing', 'Обработка на складе'), ('Delivery', 'Доставка'), ('Completed', 'Завершен'), ('Canceled', 'Отменен')], default='Received', max_length=20),
        ),
    ]
