# Generated by Django 4.2.4 on 2023-11-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_exemption_document',
            field=models.FileField(blank=True, null=True, upload_to='tax_exemption_documents/'),
        ),
    ]
