# Generated by Django 4.2.4 on 2023-09-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_additional_info_order_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('OperatorReview', 'Operator Review'), ('WarehouseProcessing', 'Warehouse Processing'), ('Delivery', 'Delivery'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Received', max_length=20),
        ),
    ]
